services:
  - type: web
    name: next-js
    runtime: node
    plan: free
    buildCommand: pnpm install; pnpm build
    startCommand: pnpm start
    autoDeploy: false
    envVars:
      - key: NODE_ENV
        value: production
